import { useEffect } from 'react';
import { BackHandler, Text, View, Vibration } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { BellRing, MapPin } from 'lucide-react-native';
import { AppButton } from '@/components/ui';
import { colors } from '@/constants';
import { disarmTrip } from '@/services/backgroundTasks';
import { useRoostopStore } from '@/store/useRoostopStore';
import { formatDistance } from '@/utils/distance';
export default function AlarmScreen() { const trip = useRoostopStore(s => s.activeTrip); const distance = useRoostopStore(s => s.alarmDistance); const dismiss = useRoostopStore(s => s.dismissAlarm); const end = useRoostopStore(s => s.endTrip); const settings = useRoostopStore(s => s.settings); useEffect(() => { if (settings.vibration) Vibration.vibrate([0,800,250,800,250,1200], true); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning); const sub = BackHandler.addEventListener('hardwareBackPress', () => true); return () => { Vibration.cancel(); sub.remove(); }; }, []); if (!trip) { router.replace('/(tabs)'); return null; } const stop = async () => { Vibration.cancel(); await disarmTrip(); end(); router.replace('/(tabs)'); }; return <View className="flex-1 bg-rooster"><SafeAreaView className="flex-1 px-6 pb-7"><View className="flex-1 items-center justify-center"><View className="h-28 w-28 items-center justify-center rounded-full bg-white/15"><BellRing size={60} color="white"/></View><Text className="mt-8 text-center text-base font-extrabold uppercase tracking-[3px] text-yolk">Cock-a-doodle-doo!</Text><Text className="mt-4 text-center text-[39px] font-black leading-[44px] text-white">YOUR STOP{`\n`}IS NEAR</Text><View className="mt-8 flex-row items-center"><MapPin size={21} color="white"/><Text className="ml-2 text-center text-xl font-bold text-white">{trip.destination.name}</Text></View><Text className="mt-3 text-center text-lg text-white/80">Approximately <Text className="font-bold text-white">{formatDistance(distance ?? trip.alertRadius)}</Text> away</Text></View><Text className="mb-5 text-center text-sm leading-5 text-white/75">Look around and prepare to get off safely.</Text><AppButton variant="secondary" title="I’m awake — dismiss alarm" onPress={() => { Vibration.cancel(); dismiss(); router.replace('/(tabs)'); }}/><AppButton className="mt-3" variant="ghost" title="Dismiss and end trip" onPress={stop}/></SafeAreaView></View>; }
