import { Linking, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { BellRing, ChevronLeft, MapPin, ShieldAlert } from 'lucide-react-native';
import { AppButton, Screen } from '@/components/ui';
import { colors } from '@/constants';
const copy = { foreground: ['Allow precise location', 'Roostop needs your location to calculate the distance to your destination.'], background: ['Allow background location', 'Choose “Allow all the time” so Roostop can watch your stop while your phone is locked.'], notifications: ['Allow notifications', 'Roostop needs notifications to show and sound your destination alarm on the lock screen.'] } as const;
export default function Permissions() { const { missing = 'background' } = useLocalSearchParams<{ missing?: keyof typeof copy }>(); const [title, body] = copy[missing] ?? copy.background; return <Screen><SafeAreaView className="flex-1 px-6 pb-7"><AppButton variant="ghost" title="Back" icon={<ChevronLeft size={20} color={colors.rooster}/>} onPress={() => router.back()} className="self-start px-0"/><View className="flex-1 justify-center"><View className="h-16 w-16 items-center justify-center rounded-full bg-red-100"><ShieldAlert size={31} color={colors.rooster}/></View><Text className="mt-6 text-[32px] font-bold text-ink">{title}</Text><Text className="mt-4 text-[17px] leading-7 text-muted">{body}</Text><View className="mt-8 gap-5"><PermissionLine icon={<MapPin size={21} color={colors.rooster}/>} text="Used only while you have an active trip"/><PermissionLine icon={<BellRing size={21} color={colors.rooster}/>} text="Needed to alert you with the screen locked"/><PermissionLine icon={<ShieldAlert size={21} color={colors.rooster}/>} text="No route trail is stored or sent to a server"/></View><View className="mt-8 rounded-app border border-yolk/50 bg-yellow-50 p-4"><Text className="text-sm leading-5 text-ink">Important: GPS, tunnels, low battery, force-stopping the app, or system restrictions can delay or prevent an alert. Stay aware of your surroundings.</Text></View></View><AppButton title="Open system settings" onPress={() => Linking.openSettings()}/><Text className="mt-4 text-center text-xs leading-5 text-muted">After changing the permission, return to Roostop and start the trip again.</Text></SafeAreaView></Screen>; }
function PermissionLine({ icon, text }: { icon: React.ReactNode; text: string }) { return <View className="flex-row items-center">{icon}<Text className="ml-3 flex-1 text-[15px] text-ink">{text}</Text></View>; }
