import { useMemo, useState } from 'react';
import { FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { ChevronLeft, MapPin } from 'lucide-react-native';
import { Screen, SearchBox } from '@/components/ui';
import { colors, SAMPLE_DESTINATIONS } from '@/constants';
import { useRoostopStore } from '@/store/useRoostopStore';
export default function SearchScreen() { const [query, setQuery] = useState(''); const select = useRoostopStore(s => s.selectDestination); const saved = useRoostopStore(s => s.saved); const data = useMemo(() => [...saved, ...SAMPLE_DESTINATIONS].filter((d, i, a) => a.findIndex(x => x.id === d.id) === i).filter(d => `${d.name} ${d.address}`.toLowerCase().includes(query.toLowerCase())), [query, saved]); return <Screen><SafeAreaView className="flex-1"><View className="flex-row items-center gap-2 px-4 py-3"><Pressable accessibilityLabel="Close search" onPress={() => router.back()} className="h-12 w-12 items-center justify-center"><ChevronLeft size={28} color={colors.ink}/></Pressable><SearchBox className="flex-1" autoFocus value={query} onChangeText={setQuery} placeholder="Search Cebu destinations"/></View><Text className="px-5 pb-2 pt-4 text-sm font-bold uppercase tracking-wider text-muted">{query ? 'Search results' : 'Suggested nearby'}</Text><FlatList data={data} keyExtractor={x => x.id} keyboardShouldPersistTaps="handled" ListEmptyComponent={<Text className="p-8 text-center text-muted">No local results. Press and hold the map to pin this place manually.</Text>} renderItem={({ item }) => <Pressable className="mx-4 flex-row items-center border-b border-line py-4" onPress={() => { select(item); router.back(); }}><View className="h-11 w-11 items-center justify-center rounded-full bg-white"><MapPin size={21} color={colors.rooster}/></View><View className="ml-3 flex-1"><Text className="text-base font-bold text-ink">{item.name}</Text><Text className="mt-1 text-sm text-muted">{item.address}</Text></View></Pressable>}/><View className="px-5 pb-6"><Text className="text-xs leading-5 text-muted">Demo search uses curated local places. Connect a Places provider through environment variables before production release.</Text></View></SafeAreaView></Screen>; }
