import { Alert, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Bookmark, MapPin, Trash2 } from 'lucide-react-native';
import { EmptyState, Screen } from '@/components/ui';
import { colors } from '@/constants';
import { useRoostopStore } from '@/store/useRoostopStore';
import { formatDistance } from '@/utils/distance';
export default function Saved() { const saved = useRoostopStore(s => s.saved), remove = useRoostopStore(s => s.removeSaved), select = useRoostopStore(s => s.selectDestination), setRadius = useRoostopStore(s => s.setAlertRadius); return <Screen><SafeAreaView className="flex-1"><View className="px-5 pb-5 pt-4"><Text className="text-[32px] font-bold text-ink dark:text-white">Saved</Text><Text className="mt-1 text-base text-muted">Start frequent trips faster</Text></View><FlatList data={saved} keyExtractor={x => x.id} contentContainerStyle={{ paddingHorizontal: 20, flexGrow: 1 }} ListEmptyComponent={<EmptyState icon={<Bookmark size={44} color={colors.rooster}/>} title="No saved stops" body="Choose a destination from Home, then save it for quick access next time."/>} renderItem={({ item }) => <Pressable onPress={() => { select(item); setRadius(item.defaultRadius); router.navigate('/(tabs)'); }} className="mb-3 flex-row items-center rounded-app border border-line bg-panel p-4"><View className="h-12 w-12 items-center justify-center rounded-full bg-red-50"><MapPin size={23} color={colors.rooster}/></View><View className="ml-3 flex-1"><Text className="text-base font-bold text-ink">{item.label}</Text><Text className="mt-1 text-sm text-muted">{item.name} · {formatDistance(item.defaultRadius)}</Text></View><Pressable accessibilityLabel={`Delete ${item.label}`} onPress={() => Alert.alert('Remove saved stop?', item.label, [{ text: 'Cancel' }, { text: 'Remove', style: 'destructive', onPress: () => remove(item.id) }])} className="p-2"><Trash2 size={20} color={colors.muted}/></Pressable></Pressable>}/></SafeAreaView></Screen>; }
