import { Pressable, ScrollView, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { BellRing, ChevronRight, LocateFixed, Moon, ShieldCheck, Smartphone, Vibrate } from 'lucide-react-native';
import { Screen } from '@/components/ui';
import { colors, RADII } from '@/constants';
import { useRoostopStore } from '@/store/useRoostopStore';
import { formatDistance } from '@/utils/distance';
export default function Settings() { const settings = useRoostopStore(s => s.settings), update = useRoostopStore(s => s.updateSettings); return <Screen><SafeAreaView className="flex-1"><ScrollView contentContainerStyle={{ paddingBottom: 40 }}><View className="px-5 pb-5 pt-4"><Text className="text-[32px] font-bold text-ink dark:text-white">Settings</Text><Text className="mt-1 text-base text-muted">Alarm, access, and appearance</Text></View><SettingsSection title="Alarm"><Row icon={<BellRing size={21} color={colors.rooster}/>} title="Default alert distance" value={formatDistance(settings.defaultRadius)} onPress={() => update({ defaultRadius: RADII[(RADII.indexOf(settings.defaultRadius) + 1) % RADII.length] })}/><ToggleRow icon={<Vibrate size={21} color={colors.rooster}/>} title="Vibration" body="Vibrate while the destination alarm is active" value={settings.vibration} onValueChange={v => update({ vibration: v })}/><ToggleRow icon={<Smartphone size={21} color={colors.rooster}/>} title="Alarm sound" body="Play the system alarm notification sound" value={settings.sound} onValueChange={v => update({ sound: v })}/></SettingsSection><SettingsSection title="Access"><Row icon={<LocateFixed size={21} color={colors.rooster}/>} title="Location & notifications" body="Review system permissions" onPress={() => router.push('/permissions')}/></SettingsSection><SettingsSection title="Accessibility"><ToggleRow icon={<Moon size={21} color={colors.rooster}/>} title="Reduce motion" body="Use simpler screen transitions" value={settings.reducedMotion} onValueChange={v => update({ reducedMotion: v })}/></SettingsSection><View className="mx-5 mt-4 rounded-app border border-line bg-panel p-4"><View className="flex-row items-center"><ShieldCheck size={22} color={colors.rooster}/><Text className="ml-2 font-bold text-ink">Privacy by default</Text></View><Text className="mt-2 text-sm leading-5 text-muted">Roostop works on-device. It stores destination and trip summaries locally and does not keep a trail of your movement.</Text></View><Text className="mt-7 text-center text-xs text-muted">Roostop 1.0.0 · Build for safe commuting</Text></ScrollView></SafeAreaView></Screen>; }
function SettingsSection({ title, children }: React.PropsWithChildren<{ title: string }>) { return <View className="mb-6"><Text className="mb-2 px-5 text-xs font-bold uppercase tracking-widest text-muted">{title}</Text><View className="mx-5 overflow-hidden rounded-app border border-line bg-panel">{children}</View></View>; }
function Row({ icon, title, body, value, onPress }: { icon: React.ReactNode; title: string; body?: string; value?: string; onPress(): void }) { return <Pressable onPress={onPress} className="min-h-16 flex-row items-center border-b border-line px-4 py-3 last:border-b-0">{icon}<View className="ml-3 flex-1"><Text className="text-[15px] font-semibold text-ink">{title}</Text>{body && <Text className="mt-1 text-xs text-muted">{body}</Text>}</View>{value && <Text className="mr-2 text-sm text-muted">{value}</Text>}<ChevronRight size={19} color={colors.muted}/></Pressable>; }
function ToggleRow({ icon, title, body, value, onValueChange }: { icon: React.ReactNode; title: string; body: string; value: boolean; onValueChange(v: boolean): void }) { return <View className="min-h-16 flex-row items-center border-b border-line px-4 py-3 last:border-b-0">{icon}<View className="ml-3 flex-1"><Text className="text-[15px] font-semibold text-ink">{title}</Text><Text className="mt-1 text-xs text-muted">{body}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{ false: colors.line, true: colors.rooster }} thumbColor="white"/></View>; }
